version: '2'
services:
  db:
    container_name: mysql
    image: mysql
    volumes:
      - ./home/atilarampazo/Documentos/projetos/data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    container_name: atila-web
    build:
      context: .
      dockerfile: Dockerfile
    image: atilarampazo/web
    volumes:
      - ./home/atilarampazo/Documentos/projetos:/var/www/html
    ports:
      - 80:80

  phpmyadmin:
    container_name: phpmyadmin  
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80