version: '2'
services:
  cache:
      image: redis
  database:
    container_name: mysql
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    container_name: atila-web
    build:
      context: .
      dockerfile: Dockerfile
    image: atilarampazo/web
    links:
        - database
        - cache
    volumes:
      - ./:/var/www/html
    
    ports:
      - 80:80

  phpmyadmin:
    container_name: phpmyadmin  
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - database
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
    
